### ISSUE TITLE
Cannot resolve module 'meteor/underscore' 

### ISSUE THREAD

**Issue by louis49** [stphdenis/meteor-client-packages-meteor#1]
Using this import : 
var _meteor = require('meteor-client-packages-meteor/meteor');

cause this error on launch : 
Module not found: Error: Cannot resolve module 'meteor/underscore'

**Comment by stphdenis** [comment]
You have to `require('meteor/meteor')` as in Meteor 1.3+ and configure `webpack.config.js` file.
See Usage, point 2 in the README.
